// <auto-generated />
using System;
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Data.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    partial class ForumAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("Name with which user is displayed in app");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Non-mandatory url of profile picture for user");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()")
                        .HasComment("Join date for user in utc time");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d926fd2-1b4e-4ea7-a019-2bcb179db8f9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff3a60e2-6fce-40ca-8ba4-a72c0d2df7c9",
                            DisplayName = "Alice",
                            Email = "alice@example.com",
                            EmailConfirmed = true,
                            JoinDate = new DateTime(2025, 6, 19, 10, 57, 14, 145, DateTimeKind.Utc).AddTicks(8937),
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE@EXAMPLE.COM",
                            NormalizedUserName = "ALICE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC9bG6Y4LAGgT2Ih3qsFwL2zHcLv4RYK0zPWYtrsi0P6bq31sMQzmxkAghrUYZ9AIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f13a7afb-c6a6-4033-895d-0805ca0cef43",
                            TwoFactorEnabled = false,
                            UserName = "alice@example.com"
                        },
                        new
                        {
                            Id = new Guid("e43bb3f7-884a-437b-9a0c-b0d181f07634"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d12c855-effd-4827-bc5b-3ec1355c8765",
                            DisplayName = "Bob",
                            Email = "bob@example.com",
                            EmailConfirmed = true,
                            JoinDate = new DateTime(2025, 6, 19, 10, 57, 14, 145, DateTimeKind.Utc).AddTicks(8960),
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB@EXAMPLE.COM",
                            NormalizedUserName = "BOB@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC9bG6Y4LAGgT2Ih3qsFwL2zHcLv4RYK0zPWYtrsi0P6bq31sMQzmxkAghrUYZ9AIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e890cdaa-ec70-457c-9678-9025d1931b90",
                            TwoFactorEnabled = false,
                            UserName = "bob@example.com"
                        });
                });

            modelBuilder.Entity("ForumApp.Data.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Board Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()")
                        .HasComment("Board creation date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasComment("Short description of the board");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Represents whether the board is deleted or not");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)")
                        .HasComment("Name of board");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5578431-7ae6-4ed9-a402-f1c3401c7100"),
                            CreatedAt = new DateTime(2025, 6, 19, 10, 57, 14, 146, DateTimeKind.Utc).AddTicks(7200),
                            Description = "Talk about anything here.",
                            IsDeleted = false,
                            Name = "General Discussion"
                        },
                        new
                        {
                            Id = new Guid("f8385f75-481b-4b70-be0e-c975265e98ba"),
                            CreatedAt = new DateTime(2025, 6, 19, 10, 57, 14, 146, DateTimeKind.Utc).AddTicks(7206),
                            Description = "Get help with your tech problems.",
                            IsDeleted = false,
                            Name = "Tech Support"
                        });
                });

            modelBuilder.Entity("ForumApp.Data.Models.BoardCategory", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of board");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of category to apply to board");

                    b.HasKey("BoardId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BoardCategories");

                    b.HasData(
                        new
                        {
                            BoardId = new Guid("c5578431-7ae6-4ed9-a402-f1c3401c7100"),
                            CategoryId = new Guid("67e8a9f8-29d7-444f-bd9b-86225ae41daf")
                        },
                        new
                        {
                            BoardId = new Guid("f8385f75-481b-4b70-be0e-c975265e98ba"),
                            CategoryId = new Guid("67e8a9f8-29d7-444f-bd9b-86225ae41daf")
                        });
                });

            modelBuilder.Entity("ForumApp.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)")
                        .HasComment("Name of category");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67e8a9f8-29d7-444f-bd9b-86225ae41daf"),
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("60f51770-93bc-42b4-a27c-8a280abda112"),
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("5fbd4e2e-a6f9-4d0f-ad91-fa2794d20317"),
                            Name = "News"
                        });
                });

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of post");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of user which posted this post");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of board to which the post belongs to");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Content of the post");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()")
                        .HasComment("Date when the post was created in UTC time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows whether the post was deleted by moderator");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit")
                        .HasComment("Shows whether the post is pinned by moderator");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()")
                        .HasComment("Last date the post was modified in UTC time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Title of the post");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BoardId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71d465ed-bd31-4c2c-9700-e1274685ca5d"),
                            ApplicationUserId = new Guid("7d926fd2-1b4e-4ea7-a019-2bcb179db8f9"),
                            BoardId = new Guid("c5578431-7ae6-4ed9-a402-f1c3401c7100"),
                            Content = "We're glad to have you here.",
                            CreatedAt = new DateTime(2025, 6, 19, 10, 57, 14, 147, DateTimeKind.Utc).AddTicks(3561),
                            IsDeleted = false,
                            IsPinned = true,
                            ModifiedAt = new DateTime(2025, 6, 19, 10, 57, 14, 147, DateTimeKind.Utc).AddTicks(3562),
                            Title = "Welcome to the forums!"
                        },
                        new
                        {
                            Id = new Guid("6523ec54-87f8-4114-b42b-4e6cb75c802a"),
                            ApplicationUserId = new Guid("e43bb3f7-884a-437b-9a0c-b0d181f07634"),
                            BoardId = new Guid("f8385f75-481b-4b70-be0e-c975265e98ba"),
                            Content = "My laptop gets very hot when gaming. Any tips?",
                            CreatedAt = new DateTime(2025, 6, 19, 10, 57, 14, 147, DateTimeKind.Utc).AddTicks(3569),
                            IsDeleted = false,
                            IsPinned = false,
                            ModifiedAt = new DateTime(2025, 6, 19, 10, 57, 14, 147, DateTimeKind.Utc).AddTicks(3570),
                            Title = "Laptop overheating issue"
                        });
                });

            modelBuilder.Entity("ForumApp.Data.Models.PostTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of the tag which applied to the post");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of the post");

                    b.HasKey("TagId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            TagId = new Guid("3b169889-2b30-47f5-81fc-4f68fb3369ba"),
                            PostId = new Guid("71d465ed-bd31-4c2c-9700-e1274685ca5d")
                        },
                        new
                        {
                            TagId = new Guid("1c326eb8-947a-41e9-a3a9-03a630af7151"),
                            PostId = new Guid("6523ec54-87f8-4114-b42b-4e6cb75c802a")
                        });
                });

            modelBuilder.Entity("ForumApp.Data.Models.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of reply");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of user which posted this reply");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Comment of reply");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()")
                        .HasComment("Date when the reply was created in UTC time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Shows whether the reply was deleted by moderator");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of the post to which the reply belongs to");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PostId");

                    b.ToTable("Replies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bded954-6e81-4e44-a7e3-19234f568f0c"),
                            ApplicationUserId = new Guid("e43bb3f7-884a-437b-9a0c-b0d181f07634"),
                            Content = "Thanks! Happy to be here.",
                            CreatedAt = new DateTime(2025, 6, 19, 10, 57, 14, 148, DateTimeKind.Utc).AddTicks(4091),
                            IsDeleted = false,
                            PostId = new Guid("71d465ed-bd31-4c2c-9700-e1274685ca5d")
                        },
                        new
                        {
                            Id = new Guid("9669f2a1-b62d-4a18-8e49-3edabb18d418"),
                            ApplicationUserId = new Guid("7d926fd2-1b4e-4ea7-a019-2bcb179db8f9"),
                            Content = "Try cleaning the fan and applying new thermal paste.",
                            CreatedAt = new DateTime(2025, 6, 19, 10, 57, 14, 148, DateTimeKind.Utc).AddTicks(4097),
                            IsDeleted = false,
                            PostId = new Guid("6523ec54-87f8-4114-b42b-4e6cb75c802a")
                        });
                });

            modelBuilder.Entity("ForumApp.Data.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id of tag which can be used in posts on a board");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Name of tag");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b53a915c-c138-4567-9718-d04f7080297d"),
                            Name = "Hot"
                        },
                        new
                        {
                            Id = new Guid("1c326eb8-947a-41e9-a3a9-03a630af7151"),
                            Name = "Discussion"
                        },
                        new
                        {
                            Id = new Guid("3b169889-2b30-47f5-81fc-4f68fb3369ba"),
                            Name = "Announcement"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ForumApp.Data.Models.BoardCategory", b =>
                {
                    b.HasOne("ForumApp.Data.Models.Board", "Board")
                        .WithMany("BoardCategories")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumApp.Data.Models.Category", "Category")
                        .WithMany("BoardCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.HasOne("ForumApp.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Posts")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumApp.Data.Models.Board", "Board")
                        .WithMany("Posts")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ForumApp.Data.Models.PostTag", b =>
                {
                    b.HasOne("ForumApp.Data.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumApp.Data.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ForumApp.Data.Models.Reply", b =>
                {
                    b.HasOne("ForumApp.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Replies")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumApp.Data.Models.Post", "Post")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ForumApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ForumApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ForumApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForumApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ForumApp.Data.Models.Board", b =>
                {
                    b.Navigation("BoardCategories");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForumApp.Data.Models.Category", b =>
                {
                    b.Navigation("BoardCategories");
                });

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Navigation("PostTags");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ForumApp.Data.Models.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
